<a href="https://colab.research.google.com/github/shanjida101/Study-Machine-Learning-/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a= np.array(4)
a #scalar (0d tensor)

array(4)

In [8]:
a.ndim

0

Axis is basically how many dimension I have.
No of axis = rank / dimension

In [11]:
#list of number is 1d tensor aka vector.
arr_1d = np.array([1, 2, 3])
arr_1d


array([1, 2, 3])

In [12]:
arr_1d.ndim #We can call this vector. Its a 1d tensor but 3d vector as there is three numbers so 3 dimension vector

1

In [7]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]]) #metrices (collection of vectors) its rank=2 = dimension
arr_2d #A 2D array is like a table with rows and columns.

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr_2d.ndim

2

In [15]:
arr_2d.shape

(2, 3)

In [6]:
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],

                   [[7, 8, 9],
                    [10, 11, 12]]])
arr_3d  #A 3D array is like a stack of 2D arrays (collection of matrices). Here is 3 axis (row,column,depth)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
arr_3d.ndim

3

In ml there is 0-5d tensor. Rank=axis=no of dimensions . Shape is in a particular axis how much items can be stored
